FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
COPY prisma/ ./
RUN npm ci
RUN npx prisma generate
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev      # prod 의존성만
COPY --from=builder /app/dist ./dist
CMD ["node", "dist/main.js"]